version: 2.1
jobs:
  publish:
    docker:
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - run: npm install -g @vscode/vsce && vsce publish -p $PAT

workflows:
  version: 2
  setup-publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context:
            - VSCODE
